
auth.token=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

defaults.org=here-ur
defaults.project=react-native

defaults.url=https://sentry.io/
